### ISSUE TITLE
Usernameless working on OsX please update website

### ISSUE THREAD

**Issue by Wesseldr** [abergs/fido2-net-lib#101]
Hi,

On the demo website: https://fido2.azurewebsites.net/usernameless  it says:
_

> Please note: At the time of writing (Feb 2019) this is only supported by Edge on Windows.

_

Since MS released Edge on OsX (pre-release), I can confirm that _Usernameless_ is now also working on OsX with Edge 👍 
[Edge for OsX](https://www.microsoftedgeinsider.com/en-us/download?platform=macos)

Could some one of the core team please update this on the website: 
https://fido2.azurewebsites.net/usernameless

Many thanks in advance,

JWR

**Comment by abergs** [comment]
Cool, will do!

**Comment by Wesseldr** [comment]
Also add the new Chrome beta (Version 76.0.3809.72 (Official Build) beta
(64-bit)),Works on your site too! :-)
Hope I'm on time so you can add them both as you update it :-)

Thank you for your excellent work!! I'm trying to implement the same in
Node currently..

Have a great day and thank you for updating the info.

Wessel
"No matter where you go, there you are" from Buckeroo Bonzai

**Comment by Wesseldr** [comment]
That is username less. for OsX on Chrome: Version 76.0.3809.72 (Official
Build) beta (64-bit)

Wessel
"No matter where you go, there you are" from Buckeroo Bonzai
