### ISSUE TITLE
HTTPS broken on demo website

### ISSUE THREAD

**Issue by prajaybasu** [abergs/fido2-net-lib#106]
Trying to register any credential on `fido2.azurewebsites.net` returns this error:  

`exception:SecurityError: The relying party ID 'www.passwordless.dev' is not a registrable domain suffix of, nor equal to 'https://fido2.azurewebsites.net'.`

Trying to visit `passwordless.dev` results in a HTTPS error:

`DLG_FLAGS_SEC_CERT_CN_INVALID`.  

I believe that the RP URI was changed recently so WebAuthn won't work from the azure subdomain. However, the custom domain remains inaccessible currently due to HSTS and an invalid SSL certificate.  

Perhaps fido2.azurewebsites.net should keep hosting another instance of the test site with the correct RP.

**Comment by abergs** [comment]
The demo url should be www.passwordless.dev and is only accessible through https.
https://www.passwordless.dev/overview works fine on my machine.

Is there still any broken link pointing to fido2.azurewebsites.net?

**Comment by Wesseldr** [comment]
@prajaybasu You're still clicking on the old link, just use the new website and all will be working again ;-)

**Comment by prajaybasu** [comment]
@abergs fido2.azurewebsites.net was one of the top results when searching for fido2 testing websites. I believe it will take some time for search engines to adapt to the new domain.  
https://www.google.com/search?q=fido2
https://duckduckgo.com/?q=fido2+test&ia=web

Anyway, it seems like you guys fixed the HTTPS certificate. fido2.azurewebsites.net is correctly redirecting to passwordless.dev with the correct HTTPS certificate (Let's Encrypt) instead of the generic Azure HTTPS certificate.

P.S: The GitHub repository description still points to fido2.azurewebsites.net (which is honestly quite a memorable name), might want to change that to the new domain.

**Comment by abergs** [comment]
@prajaybasu I see. That is fixed now
