### ISSUE TITLE
Fido2-CI fails: Submitted pull request fails on Access Denied

### ISSUE THREAD

**Issue by Wesseldr** [abergs/fido2-net-lib#109]
During the build, something goes wrong and I don;t think its my code related pull requests ;-)
It tries to publish and obviously I should not be allowed to do so with only a pull request :-)
But nevertheless the pipe fails like the pull request is failing on tests.

Below is the error..
source: https://anders.visualstudio.com/Fido2/_build/results?buildId=264

The nuget command failed with exit code(1) and error(Response status code does not indicate success: 500 (Internal Server Error - **Access Denied:** Microsoft.TeamFoundation.ServiceIdentity;b78962e5-7a67-4baf-8421-1a5b22769a16:Build:3168acd0-00be-42f9-a33a-99cbf4aadb06 needs the following permission(s) on the resource $PROJECT:vstfs:///Classification/TeamProject/3168acd0-00be-42f9-a33a-99cbf4aadb06: to perform this action: View project-level information (DevOps Activity ID: 93564C02-1F8C-4EFF-B73B-69E0D4697773)).)
Packages failed to publish

**Comment by abergs** [comment]
The NuGet push is not to Nuget, but instead to a developement feed. I have deactived it for now.
