### ISSUE TITLE
Add support for TPM

### ISSUE THREAD

**Issue by abergs** [abergs/fido2-net-lib#11]
https://medium.com/@herrjemand/verifying-fido-tpm2-0-attestation-fc7243847498

**Comment by aseigler** [comment]
Made decent progress on this tonight. I think I will have functional implementation tomorrow.

**Comment by abergs** [comment]
@aseigler you king of men! ;)

(just FYI: I've been running a conformance test tool written by the FIDO alliance. I have fixed some small bugs, updated the API and will return with new Options/Result couples for unit testing certain things in "packed" and "tpm")

**Comment by abergs** [comment]
Progress in PR #15

**Comment by aseigler** [comment]
It's as good as it is going get at the moment.  Can't really do much else until I have MDS functional.

**Comment by abergs** [comment]
What's MDS?

**Comment by aseigler** [comment]
This can probably be closed at this point.
