### ISSUE TITLE
https://fido2.azurewebsites.net site broken?

### ISSUE THREAD

**Issue by onlykey** [abergs/fido2-net-lib#112]
Tried the site a few weeks ago and everything worked great, tried the test site yesterday and today and get this error:

exception:SecurityError: The relying party ID 'www.passwordless.dev' is not a registrable domain suffix of, nor equal to 'https://fido2.azurewebsites.net'.

I tested multiple browsers and security keys so I think its an issue with the site.

**Comment by aseigler** [comment]
It's been renamed to https://www.passwordless.dev.

@abergs, https://passwordless.dev doesn't have the right cert associated.  Also, should we have https://fido2.azurewebsites.net redirect to the new site name?

**Comment by abergs** [comment]
@aseigler Redirecting from fido2.azurewebsites.net would be good.

However, the certificate for passwordless.dev is a bit complicated. I'm using https://github.com/sjkp/letsencrypt-azure to generate them for free, however the current implementation only work for LE wildcard certificates and they do unfortunately not include the root domain. See more details here: https://github.com/sjkp/letsencrypt-azure/issues/8

**Comment by aseigler** [comment]
I am very familiar with that package, you can use San and SNI instead of wildcard.

**Comment by abergs** [comment]
Oh! I just made a experimental PR to enable the root domain aswell... currently trying to figure out how to test it...
