### ISSUE TITLE
Fido2.AspNet is not published as a package

### ISSUE THREAD

**Issue by PeterStaev** [abergs/fido2-net-lib#136]
Any reason why the Fido2.AspNet is not published as a nuget package?

**Comment by mackie1001** [comment]
I think it's all ready to go (it was part of a PR I did) - @abergs do you need anything from me to progress this?

**Comment by abergs** [comment]
I’m back from vacation so I will be reviewing things in the coming days.
    	
    	

    	Get Outlook for iOS
    
  




On Fri, Dec 20, 2019 at 3:37 PM +0100, "Paul McNamara" <notifications@github.com> wrote:












I think it's all ready to go (it was part of a PR I did) - @abergs do you need anything from me to progress this?

**Comment by ewassef** [comment]
Any updates on this?

**Comment by abergs** [comment]
Fixed https://www.nuget.org/packages/Fido2.AspNet/
