### ISSUE TITLE
Error with Android SafetyNet AttestationFormat

### ISSUE THREAD

**Issue by redhook62** [abergs/fido2-net-lib#137]
Hi,

When using a Samsung mobile with Samsung Pass for biometric authentication, at registration JwtSecurityToken cause an exception.

AndroidSafetyNet.cs - AndroidSafetyNet.Verify()
IDX12729: Unable to decode the header

**Header**
`{
  "alg": "RS256",
  "x5c": [ 2 certificates from google]
} 
`
**Payload**
`{
  "nonce": "69U9PFuBsLfFrI7aJg8q3P+kTWgJDVoOHvcrZqFG0pc=",
  "timestampMs": 1574959428858,
  "apkPackageName": "com.google.android.gms",
  "apkDigestSha256": "rTlKdfWU/r7vjK6sH3C1Jfn5mRSC1HUStqJ4WX1vWFE=",
  "ctsProfileMatch": true,
  "apkCertificateDigestSha256": [
    "8P1sW0EPJcslw7UzRsiXL64w+O50Ed+RBICtay1g24M="
  ],
  "basicIntegrity": true
}`

Parameters are

- AuthenticatorAttachment="" 
- AttestationConveyancePreference="direct" // or indirect
- UserVerificationRequirement="preferred" 
- Extensions="true" 
- UserVerificationIndex="true" 
- Location="true" 
- UserVerificationMethod="true" 
- RequireResidentKey="false"

![image](https://user-images.githubusercontent.com/26826945/69823335-db822800-1208-11ea-8f65-beeae93d016b.png)

- Browser is Android Chrome version 78.0.3904.108
- Android 9.0
- Server FW 4.7.2 Windows 2019

Any Ideas ?

Regards

**Comment by redhook62** [comment]
Solved ! for the momment...

The problem was Newtonsoft.json version 10.0.x which was required for System.IdentityModel.Tokens.Jwt (version 5.2.4 and Up)
I also Revert Base64UrlConverter to standard Type - Non generic: JsonConverter.

I don't think if your solution works at well with framework 4.7.2. and signed assemblies.
I'm working on an implementation for ADFS whitch require signed assemblies.

Best Regards

**Comment by aseigler** [comment]
I am interested in helping you get this working the way you need it to. I really want to see an ADFS adapter for on prem that can authenticate users who have registered FIDO2 security keys with WHfB in Azure AD.

**Comment by redhook62** [comment]
At this time, I am integrating your solution, and it is going pretty well. 
You will see some screenshots below.

I will publish a new branch for a version 2.5 alpha before Christmas. 
Because I still have a few things to put in place so that it is easily usable and testable. 
Your expertise will be welcome.

The first tests are good, with FIDO keys, A Brio WebCam, or just the fingerprint readers present on PCs, tests with Android mobiles are also good.

This Alpha version will probably only work in memory with DemoStorage, SimpleMetadataService and StaticMetadataRepository.

Eventually, the Storage will be ADDS or SQLServer as supported today. SQLServer side no worries in sight, but For ADDS it's still in reflection.
Of course, I want to be able to manage several devices per user (up to 10 probably), PC, Tablet, Phone, professional or personal.

Regards

![image](https://user-images.githubusercontent.com/26826945/70184282-d0873600-16e7-11ea-95fb-9c3d33854378.png)

![image](https://user-images.githubusercontent.com/26826945/70184726-b8fc7d00-16e8-11ea-8ef7-627ab0f75816.png)

**Comment by aseigler** [comment]
The storage is the thing I want to change, particularly for this application.  Windows Hello for Business uses [msDS-KeyCredentialLink](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-ada2/45916e5b-d66f-444e-b1e5-5b0666ed4d66).  The feature that allows you to add FIDO2 security keys to an Azure AD user, when that data is replicated inbound to on prem domain controllers, that is the attribute it goes into.  Theoretically, you should be able to [use the data in that attribute](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Documentation/PowerShell/Get-ADKeyCredential.md#example-4) as the data store.  It should be pretty easy the way we built this to make it work, I just haven't found the time/motivation to actually make it a reality.  But that was basically [one of my main goals](https://github.com/abergs/fido2-net-lib/issues/68) when I was starting to get involved with this.

**Comment by redhook62** [comment]
Hi,

Thank you for the tip ! I will use it.

On the other hand, people who are not in version 2016 for ADDS (v85), it will be necessary that I limit them to a single possibility, and that for those who wish to modify their ADDS Schema (which is rare, and often "complicated") it will eventually provide them the necessary scripts.

thanks again
