### ISSUE TITLE
online demo not working without www. (wrong cert)

### ISSUE THREAD

**Issue by My1** [abergs/fido2-net-lib#139]
without www it apparently seems to load the wrong cert (issued to "*.azurewebsites.net"), this is even more frustrating when some users dont actually enter www (like me) or browser just ax the www from the URLbar.

![image](https://user-images.githubusercontent.com/6696524/69898161-b0f1b580-1355-11ea-9e67-e7b9e9b3b295.png)

**Comment by abergs** [comment]
This is now finally fixed. Gave up figuring out the LE + Azure setup (https://github.com/sjkp/letsencrypt-azure/pull/9) and just placed passwordless.dev behind cloudflare.
