### ISSUE TITLE
`RequestNewCredential` returns `CredentialCreateOptions` where enums are integers.

### ISSUE THREAD

**Issue by adyavanapalli** [abergs/fido2-net-lib#140]
The following is the method in my controller:

```cs
[HttpGet("users/{userId}/creation-options")]
public async Task<ActionResult<CredentialCreateOptions>> GetPublicKeyCredentialCreationOptions(int userId)
{
    var user = await _webAuthnApiDbContext.Users.FindAsync(userId);
    if (user == null)
    {
        return NotFound();
    }
    var fido2User = new Fido2User
    {
        DisplayName = user.DisplayName,
        Id = Encoding.UTF8.GetBytes(user.Username),
        Name = user.Username
    };
    return _fido2.RequestNewCredential(fido2User,
                                       null,
                                       AuthenticatorSelection.Default,
                                       AttestationConveyancePreference.None);
}
```

, which produces the following JSON:

```json
{
  "rp": {
    "id": "localhost",
    "name": "localhost",
    "icon": null
  },
  "user": {
    "name": "john.smith@gmail.com",
    "id": "am9obi5zbWl0aEBnbWFpbC5jb20=",
    "displayName": "John Smith"
  },
  "challenge": "iIKfvEZr+mC6+pzPcMzBVQ==",
  "pubKeyCredParams": [
    {
      "type": 0,
      "alg": -7
    },
    {
      "type": 0,
      "alg": -257
    },
    {
      "type": 0,
      "alg": -37
    },
    {
      "type": 0,
      "alg": -35
    },
    {
      "type": 0,
      "alg": -258
    },
    {
      "type": 0,
      "alg": -38
    },
    {
      "type": 0,
      "alg": -36
    },
    {
      "type": 0,
      "alg": -259
    },
    {
      "type": 0,
      "alg": -39
    }
  ],
  "timeout": 60000,
  "attestation": 0,
  "authenticatorSelection": {
    "authenticatorAttachment": null,
    "requireResidentKey": false,
    "userVerification": 1
  },
  "excludeCredentials": [],
  "extensions": null,
  "status": "ok",
  "errorMessage": ""
}
```

Notice that the keys `attestation` and `authenticatorSelection.userVerification` are integers, but the specification requires that these be strings.

I see that in the demo controller provided the response object, `CredentialCreateOptions`, is wrapped with a call to `Json`, but I've tried that and I see no difference.

**Comment by abergs** [comment]
What version of Fido2 are you running?

**Comment by abergs** [comment]
What happens if you explicitely set it?

https://github.com/abergs/fido2-net-lib/blob/master/Demo/Controller.cs#L70

Might be a bug in the default setting

**Comment by abergs** [comment]
Or how that the custom JsonConverter does not run in your environment.

**Comment by adyavanapalli** [comment]
@abergs 

> What version of Fido2 are you running?

I'm not sure what you mean by this. I'm using this repo i.e. [fido2-net-lib](https://github.com/abergs/fido2-net-lib), so I assume it's Fido2. I'm also using the preview Nuget package `1.1.0-preview2`.

**Comment by adyavanapalli** [comment]
Additionally, I'm using this API with .NET Core 3.1. I wonder if that's an issue.

**Comment by abergs** [comment]
@adyavanapalli Yeah I believe this is the JsonFormatter. The current version is based on Json.NET and not the new serializer System.Text.Json.

**Comment by adyavanapalli** [comment]
Understood.

**Comment by abergs** [comment]
You can add Newtonsoft back in a single line of code, could you test it out? https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/?WT.mc_id=-blog-scottha

**Comment by adyavanapalli** [comment]
Sure, I can check this weekend if I get some free time.

**Comment by adyavanapalli** [comment]
> You can add Newtonsoft back in a single line of code, could you test it out? https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/?WT.mc_id=-blog-scottha

Reading this again, I'm not sure what you mean. Did you mean I need to modify your source code to use the new `System.Text.Json` JSON serializer or modify my controller method?

**Comment by abergs** [comment]
@adyavanapalli Modify which JsonFormatter your api is using. The library is currently dependent on Newtonsoft which can be "added back" as the article describes.

**Comment by adyavanapalli** [comment]
@abergs This does indeed fix the issue. Thanks!
