### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by ewassef** [abergs/fido2-net-lib#142]
I haven't seen much movement on this in a while and pulling the code down and running it doesn't seem to work immediately. Also, looks like there is a missing NuGet package. 
Is this project dead? Is this project looking for a new home? Is it looking for contributors?

I would like to know before we pull it in and start using it.

**Comment by aseigler** [comment]
It's still being worked on, I've just been busy with some other priorities lately.  Currently I have been working on full tests for all attestation types for #141.  I have none and packed complete, and TPM mostly complete, just haven't made them available yet, probably should do that.

I wasn't aware of missing NuGet package, @abergs?.  We're always happy to get contributions!  Not really looking for a new home that I know of, but anything's possible.

**Comment by ewassef** [comment]
That is great to hear! This project is amazing and in my opinion, something that all serious site owners should implement. Well done! 

I have a fork with the project converted to .net core 3.1 and the libraries converted to .NET standard 2.0 and 2.1. I have also added the NuGet packages on the 3 main projects.

**Comment by ewassef** [comment]
Pull request here https://github.com/abergs/fido2-net-lib/pull/143
