### ISSUE TITLE
Upgrade to System.IdentityModel.Tokens.Jwt 6.5.0 has broken the Fido2MetadataServiceRepository

### ISSUE THREAD

**Issue by mackie1001** [abergs/fido2-net-lib#153]
It looks like the implementation of `JArray` used by `JwtSecurityToken` has been switched to an internal non-Newtonsoft one as of the latest version and this has broken `DeserializeAndValidateToc` which casts JWT properties to that type. 

This crept in because I updated another package that brought in 6.5.0. The version currently referenced in 5.6.0.

Want me to do a PR for this?

**Comment by abergs** [comment]
Thanks for the report! When does this problem manifest itself, do you have a repro?

**Comment by mackie1001** [comment]
Basically if I reference `fido2-net-lib` but upgrade all packages (I depend on System.IdentityModel.Tokens.Jwt elsewhere) to latest via the package manager then it breaks as it binds against the newer version at runtime. This came about as I'm updating my current solution (which was using a version pre-my PR) to .Net Core 3.1 and updating all other dependencies to match.

I've worked around it for now by explicitly referencing 5.6.0 in my solution.

**Comment by mackie1001** [comment]
PR #156 created for this.

**Comment by aseigler** [comment]
This same problem also impacts SafetyNet attestation type verification as it uses JArray as well.

**Comment by aseigler** [comment]
This is fixed, verified.  Thanks!
