### ISSUE TITLE
ECDsa signature not a valid DER sequence

### ISSUE THREAD

**Issue by tarun14110** [abergs/fido2-net-lib#154]
I am developing my own custom U2F for webauthn. It's working with other demo websites but getting an error while registering with https://www.passwordless.dev/. The error I'm getting is "ECDsa signature not a valid DER sequence". I'm using window crypto API for signing. 

I have been trying to encode it properly that can be verified by OpenSSL properly but couldn't get it done. Is it feasible to interoperate between windows crypto API and OpenSSL?

Signing code I'm using:

```
    public async sign(data: Uint8Array): Promise<any> {
        if (!this.privateKey) {
            throw new Error('no private key available for signing');
        }
        return window.crypto.subtle.sign(
            this.getKeyParams(),
            this.privateKey,
            data, //new TextEncoder().encode(data),
        );
    }

    private getKeyParams(): EcdsaParams {
        return { name: 'ECDSA', hash: coseEllipticCurveNames[ECDSA.ellipticCurveKeys[this.algorithm]] };
    }

    private async toCOSE(key: CryptoKey): Promise<Map<number, any>> {
  
        const exportedKey = await window.crypto.subtle.exportKey('jwk', key);
        const attData = new Map();
        attData.set(1, 2); // EC2 key type
        attData.set(3, this.algorithm);
        attData.set(-1, ECDSA.ellipticCurveKeys[this.algorithm]);
        attData.set(-2, base64ToByteArray(exportedKey.x, true));
        attData.set(-3, base64ToByteArray(exportedKey.y, true));
        return attData;
    }
```

**Comment by aseigler** [comment]
The only way you can get that particular error is when a signature with an EC2 key type is not properly ASN.1 encoded DER sequence. Specifically, the [first byte is not 0x30](https://github.com/abergs/fido2-net-lib/blob/a3df48b2b1b1cdfc6d015d50b198bf2cf1af5f4d/Src/Fido2/CryptoUtils.cs#L100).

See also:

- https://www.w3.org/TR/webauthn/#signature-attestation-types
- https://tools.ietf.org/html/rfc3279#section-2.2.3
- https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-raw-message-formats-v1.2-ps-20170411.html#registration-example
- https://crypto.stackexchange.com/questions/1795/how-can-i-convert-a-der-ecdsa-signature-to-asn-1
- https://superuser.com/questions/1023167/can-i-extract-r-and-s-from-an-ecdsa-signature-in-bit-form-and-vica-versa
- https://stackoverflow.com/questions/38702169/c-sharp-ecdsacng-signdata-use-signature-in-openssl

**Comment by tarun14110** [comment]
Thanks @aseigler  for these pointers. After converting into DER encoding I am getting error `Invalid packed attestation signature`. 
As an example from my logs 
The initial signature was [139, 174, 115, 195, 82, 75, 246, 158, 168, 239, 58, 100, 27, 13, 97, 234, 137, 115, 110, 90, 17, 20, 24, 48, 243, 47, 33, 151, 249, 14, 54, 0, 103, 219, 136, 16, 31, 24, 73, 245, 250, 159, 207, 29, 141, 205, 156, 36, 43, 152, 56, 77, 170, 89, 58, 238, 242, 39, 67, 18, 32, 184, 61, 240]

r = 008bae73c3524bf69ea8ef3a641b0d61ea89736e5a11141830f32f2197f90e3600
s = 67db88101f1849f5fa9fcf1d8dcd9c242b98384daa593aeef227431220b83df0

DER signature = 30 45 02 21 008bae73c3524bf69ea8ef3a641b0d61ea89736e5a11141830f32f2197f90e3600 02 20 67db88101f1849f5fa9fcf1d8dcd9c242b98384daa593aeef227431220b83df0

returned Uint8Array Signature = [48, 69, 2, 33, 0, 139, 174, 115, 195, 82, 75, 246, 158, 168, 239, 58, 100, 27, 13, 97, 234, 137, 115, 110, 90, 17, 20, 24, 48, 243, 47, 33, 151, 249, 14, 54, 0, 2, 32, 103, 219, 136, 16, 31, 24, 73, 245, 250, 159, 207, 29, 141, 205, 156, 36, 43, 152, 56, 77, 170, 89, 58, 238, 242, 39, 67, 18, 32, 184, 61, 240]

Do you have any suggestions for what I might be doing wrong?

**Comment by aseigler** [comment]
Two issues:

- You said U2F earlier, but now you're talking packed. Which are you using? Doesn't actually matter for the problem you're having, but trying to understand what you're working on, and guidance might vary accordingly.

- The sample r integer value has leading zeroes, that is not allowed in ASN.1.

**Comment by tarun14110** [comment]
- I am developing a WebAuthn authenticator.
- I prepended r with an extra 0x00 because the first byte of r was >0x7F. I was following https://crypto.stackexchange.com/questions/57731/ecdsa-signature-rs-to-asn1-der-encoding-question

**Comment by tarun14110** [comment]
I have attached my crypto file if it can help to better point out the problem. From this file, I call getCompatibleKey(PublicKeyCredentialParameters) and sign() functions. I convert to ASN.1 encoding in my sign function itself.

[crypto.txt](https://github.com/abergs/fido2-net-lib/files/4498093/crypto.txt)

Just for reference, This file initially taken from https://github.com/chrome-key/ckeyand modified a bit.

**Comment by aseigler** [comment]
> * I am developing a WebAuthn authenticator.
> * I prepended r with an extra 0x00 because the first byte of r was >0x7F. I was following https://crypto.stackexchange.com/questions/57731/ecdsa-signature-rs-to-asn1-der-encoding-question

Ah, yes, the encoding is good now. I will take a further look when I get a chance.

**Comment by tarun14110** [comment]
Thanks for helping through. It's working now. There was some issue the way I was returning the signature form 'then'.
