### ISSUE TITLE
Question: difference between the current code base and the WebAuthn specification

### ISSUE THREAD

**Issue by thuannguy** [abergs/fido2-net-lib#155]
Hi,
I have tried this project out and it works great for me so far. When I look into its code and compare it to the latest WebAuthn specification at https://www.w3.org/TR/webauthn/, I find many differences. Some examples are:

- The type PublicKeyCredentialCreationOptions is named CredentialCreateOptions. 
- The type PublicKeyCredentialUserEntity is named Fido2User

I guess one of the reasons is that this project wants to be backward compatible to the Fido2 spec. Other than that, are there any reasons for not making this one fully follow the WebAuthn spec? Or is it part of roadmap? I'm trying to get to know the design idea of this project 😄

**Comment by aseigler** [comment]
Early on, we were more interested in getting something working than having things named correctly. As the project evolved, we got better and better about naming things exactly the same as the Webauthn spec, but we haven't gone back and renamed everything yet.

**Comment by thuannguy** [comment]
I got it 😄 
Thank you,
Thuan.
