### ISSUE TITLE
Add more defensive exceptions

### ISSUE THREAD

**Issue by abergs** [abergs/fido2-net-lib#16]
We pass a lot of the "Expect failure" tests in the conformance tool, e.g:

![image](https://user-images.githubusercontent.com/357283/44121807-8b864e80-a021-11e8-846c-157526576af9.png)

But it's often because of null reference etc. Might be better for a library consumer if we threw more precise exceptions.

**Comment by aseigler** [comment]
Put in a good amount of this.

**Comment by abergs** [comment]
Do we have many more to add or should we go ahead and close? (unable to run the testing tool for a couple of days)

**Comment by abergs** [comment]
I think we should go ahead and close this now. Please reopen if you deem necessary.
