### ISSUE TITLE
Server-ServerAuthenticatorAttestationResponse-Resp-1 / 3 / 5

### ISSUE THREAD

**Issue by mamatomarco** [abergs/fido2-net-lib#179]
Good afternoon,
when i run the TestController against the Conformance Tool (MakeCredential Request, MakeCredential Response), everything goes fine except for:
- Server-ServerAuthenticatorAttestationResponse-Resp-1 (P-1)
- Server-ServerAuthenticatorAttestationResponse-Resp-3 (P-1)
- Server-ServerAuthenticatorAttestationResponse-Resp-5 (P-1, P-2)

Attached you'll find the errors. It seems something related to the Json Formatter (i'm using Netwonsoft).

Any idea?
<img width="710" alt="Schermata 2020-06-11 alle 17 38 37" src="https://user-images.githubusercontent.com/66791114/84407761-8db09880-ac0b-11ea-8ecd-59107c5615d8.png">
<img width="701" alt="Schermata 2020-06-11 alle 17 38 49" src="https://user-images.githubusercontent.com/66791114/84407769-8ee1c580-ac0b-11ea-903c-b74a7a21ea60.png">
<img width="701" alt="Schermata 2020-06-11 alle 17 38 57" src="https://user-images.githubusercontent.com/66791114/84407771-8f7a5c00-ac0b-11ea-8a9c-712de799dc37.png">

**Comment by aseigler** [comment]
Your best bet for debugging this is pressing the configuration link in the upper right corner of the conformance tool and clicking the "open inspector" link.  This should open up familiar looking web debugging tools.  The "P-*" tests are the positive tests, the "F-*" ones are negative and the negative ones will pass for any negative status, not just a successfully handled error.
![image](https://user-images.githubusercontent.com/6605560/84408678-70170b00-abda-11ea-9ef3-4f0556d674a8.png)

**Comment by mamatomarco** [comment]
Thank you for the fast reply, so even if i'm getting the positive ones failing (my case i've attached the screenshots) you think the FIDO tests will pass anyway? From your screenshot i see the tests pass without failures (with the green flag) but this doesn't happened to me

**Comment by aseigler** [comment]
The library will pass 100% if you have everything configured correctly.  You do need to press the "download server metadata" button and save the JSON files into a folder named "Conformance" and configure an environment variable named "fido2:MDSCacheDirPath" pointing to the folder containing the Conformance folder.  In the box that says "Server URL" you need to enter the URL you are serving the demo site out of, like https://localhost:44329 for example.
![image](https://user-images.githubusercontent.com/6605560/84412781-ba4dbb80-abdd-11ea-98ba-0f47786ec68f.png)

**Comment by mamatomarco** [comment]
Thanks a lot, everything is ok now and all the tests have been passed. Yes i know all the steps necessary to let it work, it was enough for me to download the metadata again.
Thanks again
