### ISSUE TITLE
Error with Infinion TMP (id:49465800)

### ISSUE THREAD

**Issue by redhook62** [abergs/fido2-net-lib#189]
Hi @aseigler 

I'll come back to you, it's not urgent.
I had a problem when using an Infinion TPM (id: 49465800).
In fact by reinstalling an HP laptop, the internal TPM has been activated, so the disks are BitLocked, 
before the type of attestation was PACKED and now obviously it is TPM.
So I was forced to slightly modify the source of TPM.cs.

In the SANFromAttnCertExts procedure
``` C#
generalName.CheckConstructed();
generalName.CheckNumSub (1);
                        
var exp = generalName.GetSub (0);
exp.CheckConstructed ();
// exp.CheckNumSub (1);                        // id: 49465800 'IFX' Infinion check number is wrong: 3
exp.CheckTag (AsnElt.SEQUENCE);

var directoryName = exp.GetSub (0);
directoryName.CheckConstructed ();
// directoryName.CheckNumSub (3);      // id: 49465800 'IFX' Infinion check number is wrong: 1
directoryName.CheckTag (AsnElt.SET);
```

in the Verify procedure

``` C#
// Best I can figure to do for now ?  // id:49465800 'IFX' Infinion  Model and Version are empty
// if (string.Empty == tpmManufacturer || string.Empty == tpmModel ||string.Empty == tpmVersion)
if (string.Empty == tpmManufacturer)
{
     throw new VerificationException("SAN missing TPMManufacturer, TPMModel, or TPMVersion from TPM attestation certificate");
}
```
Do you have an opinion on this

Regards

redhook

**Comment by aseigler** [comment]
Check out this PR, I think it is directly related to what you're talking about: https://github.com/abergs/fido2-net-lib/pull/187

**Comment by redhook62** [comment]
@aseigler 

Thank you, now it works fine !

Regards

**Comment by aseigler** [comment]
Glad to hear it, that one was...fun.
