### ISSUE TITLE
How the lib know the saved fingerprint in current device ?

### ISSUE THREAD

**Issue by saleeb** [abergs/fido2-net-lib#196]
Hi abergs
can you show me how the device get the saved fingerprint from device itself not from database,
in MakeCredentialOptions the fingerprint popup know my saved fingerprint and tell hello 'user' the it go to MakeCredential to save the options and public key in DB . 

i need to know if the lib can get the saved fingerprint in the device itself , i means not register it first such as demo . 

Thanks

**Comment by aseigler** [comment]
How authenticators collect and store details such as fingerprint is specific to the device, and not something the demo site or library would have access to.
