### ISSUE TITLE
Credential ID changes after calling MakeNewCredentialAsync

### ISSUE THREAD

**Issue by rcheung9** [abergs/fido2-net-lib#203]
I'm new to FIDO2/WebAuthn so I'm following the demo.  Maybe I'm misunderstanding how this works.

After I create a new credential with this code

```
const cred = await navigator.credentials.create({
        publicKey: options
}) as any
```

I get `o53X9k6huUy7H_gE-0S_A7vms-N-18axFA8Bf11HuII` for `cred.id`.  I then make the following changes and submit these changes to the FIDO2 server.

```
const credential = { } as any
credential.id = cred.id
credential.type = cred.type
credential.rawId = base64url.encode(cred.rawId)

if (cred.response) {
	const clientDataJSON = base64url.encode(cred.response.clientDataJSON)
	const attestationObject = base64url.encode(cred.response.attestationObject)
	credential.response = {
		clientDataJSON,
		attestationObject,
	}

	const regCredResponse = await this.axios.post('/Account/RegisterCredential', credential)

	localStorage.setItem(`credId`, credential.id)
	localStorage.setItem(`credId2`, regCredResponse.data.result.credentialId)
}
```

The FIDO2 server takes the credential object and calls this function

`var success = await fido2.MakeNewCredentialAsync(attestationResponse, options, callback);`

I return the `success` variable back to the client.  The resulting `credentialId` is now `o53X9k6huUy7H/gE+0S/A7vms+N+18axFA8Bf11HuII=`

Is this right? How did it change?

Before: `o53X9k6huUy7H_gE-0S_A7vms-N-18axFA8Bf11HuII`
After: `o53X9k6huUy7H/gE+0S/A7vms+N+18axFA8Bf11HuII=`

It looks similar enough, but the `-` became `+` and the `_` became `/` and it ends with a `=`.  Is this Base64 encoded? Decoding it doesn't work.

**Comment by abergs** [comment]
yes, it's base64 vs base64url encoding.
