### ISSUE TITLE
Tag v1.1.0 in this repository?

### ISSUE THREAD

**Issue by rgl** [abergs/fido2-net-lib#206]
Can you please tag the releases in this repository?

From reading the https://www.fuget.org/packages/Fido2/1.1.0 it seems the v1.1.0 tag should be set in https://github.com/abergs/fido2-net-lib/commit/c4ace0c0d9e6b3c8d6248f0e2e2724f1c24cd79a.

Having  a tag makes things easier to compare and evaluate the differences between versions/master.

**Comment by abergs** [comment]
Hi @rgl,
That's true.
Since the 1.1 release we've done a lot of work on the release mechanisms, with automatic release notes etc.

It's a slump on my part that 2.0 is not pushed as stable (it's available as preview). I will make sure it is so that subsequent releases follows suit.
