### ISSUE TITLE
MDS2 TOC Root cert change and support for RSA X5c certificates

### ISSUE THREAD

**Issue by rodheath** [abergs/fido2-net-lib#222]
Until MDS3 is fully working the changes made to replace the MDS2 TOC root certificate are needed.
Additionally, the certificates in the X5c data have moved from using ECC to RSA security keys.

**Comment by mackie1001** [comment]
How did I not notice this before I raised mine?! Anyway, it's a simple fix and I'll keep an eye on the MDS3 stuff. I just got an email from Yuriy saying details should be out in the middle of may. It's also safe to cache the existing MDS until MDS3 is on stream as it will not be getting further entries.

**Comment by aseigler** [comment]
Very odd to cut over infrastructure like that without much (any?) notice or warning...

**Comment by rodheath** [comment]
Alex,

Please accept my apologies for any inconvenience caused – this is the first time I have tried to do a pull request and was confused by the failure raised by the label checking script.

Kind regards,

Rod

From: Alex Seigler ***@***.***>
Date: Thursday, 22 April 2021 at 19:41
To: abergs/fido2-net-lib ***@***.***>
Cc: Roderick Heath ***@***.***>, State change ***@***.***>
Subject: Re: [abergs/fido2-net-lib] MDS2 TOC Root cert change and support for RSA X5c certificates (#222)

Very odd to cut over infrastructure like that without much (any?) notice or warning...

**Comment by aseigler** [comment]
Fixed by #225, thanks!
