### ISSUE TITLE
Need to add two more properties to AttestationVerificationSuccess

### ISSUE THREAD

**Issue by aseigler** [abergs/fido2-net-lib#27]
Attestation type: 

From https://www.w3.org/TR/webauthn/#attestation-type

Based on https://www.w3.org/TR/webauthn/#sctn-attestation-types, seems like string, one of "Basic", "Self", "AttCA", "ECDAA", or "None" 

Trust path:

https://www.w3.org/TR/webauthn/#attestation-trust-path
Seems like could be empty, a byte array (ECDAA) or a number of byte arrays (x5c where x5c has multiple values).

**Comment by abergs** [comment]
Why do we need them in? Are they needed as parameters to the assertion step?

**Comment by abergs** [comment]
Alright. But there doesn't seem to be very defined values.

I guess we could use a TypedString with values from the paranthesis is https://www.w3.org/TR/webauthn/#sctn-attestation-types

- Basic
- Self
- None
- AttCa
- etc..

Should the trustpath be an array of byte arrays maybe?

**Comment by aseigler** [comment]
I don't know what the trust path is supposed to look like either.  Definitely something that will need to be researched.

**Comment by aseigler** [comment]
I now have a better understanding of the wording used. We do not need these after all in AttestationVerificationSuccess, but they are needed for step 16 in VerifyAsync. This can be closed out as well.
