### ISSUE TITLE
Refactor MDS to an interface (making it injectable and optional)

### ISSUE THREAD

**Issue by abergs** [abergs/fido2-net-lib#45]
Let's implement an interface over our MDS class and break it out to a configuration property to make sure it's swappable.

**Comment by aseigler** [comment]
I'm not 100% certain what you mean here. Validating authenticator against MDS is not optional: 

https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-server-v2.0-rd-20180702.html#validating-attestation

"Servers MUST support the validation of attestation through the FIDO Metadata Service [FIDOMetadataService]."

**Comment by abergs** [comment]
I can see cases where we don't want to runt the MDS service, for example in unit tests?

And the WebAuthn Spec contradicts the fido2 spec a bit on the requirement of using their service to validate the authenticator:

> If validation is successful, obtain a list of acceptable trust anchors (attestation root certificates or ECDAA-Issuer public keys) for that attestation type and attestation statement format fmt, from a trusted source or from policy. **For example, the FIDO Metadata Service [FIDOMetadataService] provides one way** to obtain such information, using the aaguid in the attestedCredentialData in authData.

The reason why I ran into this now was to do a test run but I have no accesstokens configured, so it crashes on a nullpointer exception [here](https://github.com/abergs/fido2-net-lib/blob/master/fido2-net-lib/MetadataService.cs#L342)

**Comment by aseigler** [comment]
Ah, I should have checked _accessToken and _cacheDir for null before using them.  I think we should fix by throwing a warning if one of those is not available but allowing execution to continue.

It is interesting how the two specifications sometimes seem to compliment and conflict at the same time.

**Comment by abergs** [comment]
Haha I agree - especially when the conformance tests contradicts them BOTH! 👌 

I would like to make two major changes:

1. Implement a interface + method, e.g:
```
Interface MetadataService {
MetadataTOCPayloadEntry GetEntry(guid aaguid)
}
```
and use that method [here](https://github.com/abergs/fido2-net-lib/blob/master/fido2-net-lib/AuthenticatorAttestationResponse.cs#L541)
2. Move the `MDSMetadata.Instance()` (that returns above interface) to the constructor of the fido2.net lib and store pass it to VerifyAsync as an argument.

And I agree with your suggestion.

With those changes it would be trivial to add the interface to the configuration and make the Metdataservice swappable for whatever reason the RP would want to change the provider (firewalled server etc)

**Comment by abergs** [comment]
I also believe a developer(RP) should be able to temporarily disable the MDS step for testing purposes and we should not fail the validation, but throw/log a warning or error.

This is useful in order to decrease the friction of getting started with FIDO2. I'm imagining a user case where I just want to install the package and see if I can get the Demo working over the weekend just to try it out. I don't think we should force them to register for an accesskey just to test the lib, right?

**Comment by aseigler** [comment]
Oh, absolutely.  The intent was not to make any casual user go get an access token.

**Comment by abergs** [comment]
PR in #47
