### ISSUE TITLE
Consider replacing WebClient with HttpClient in Metadataservice

### ISSUE THREAD

**Issue by abergs** [abergs/fido2-net-lib#49]
and maybe add `using` statements.

Also add optional support for the RP to provider their own instance of HTTPClient (because of socket control?).

Reasons to do this are listed in this SO answer: https://stackoverflow.com/questions/20530152/deciding-between-httpclient-and-webclient

**Comment by aseigler** [comment]
Sounds perfectly reasonable to me.

**Comment by aseigler** [comment]
I started looking into this, but HttpClient is not available in net472.  Open to suggestions on how to proceed.

**Comment by CodeTherapist** [comment]
@aseigler How did you came to the conclusion that [HttpClient is not support for net472](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.7.2)? Or did I missed something here?

**Comment by aseigler** [comment]
Interesting. I tried to add an HttpClient object and intellisense indicated it was available for netstandard and netcore but not available in net472, and I did not investigate further. Now I will do so.

**Comment by CodeTherapist** [comment]
@aseigler Hmm, that's strange! just try to build it (perhaps `dotnet restore` does also help).

**Comment by abergs** [comment]
Just briefly checked the commit.

We should really not block with .Result. See Sync over Async: https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait

**Comment by aseigler** [comment]
Yeah, I couldn't figure out a better way to do this with HttpClient. Under normal conditions, this stuff only executes on first access on startup, and only if an access token or cache directory is provided. It downloads the official table of contents (a few kilobytes), then downloads metadata statements (a few kilobytes) for objects with AAGUID. Currently, that's it. If the conformance testing endpoints are used, FAR more is downloaded.

If anyone has recommendations on how to do this right, I am open to suggestions.

**Comment by abergs** [comment]
I think one way would be to refactor the MDS service to allow a sync read only access and a async way to initialize data.

**Comment by aseigler** [comment]
Makes sense. It's kinda set up for that already, actually. Should not be too complicated I hope.

**Comment by aseigler** [comment]
How does this look?  https://github.com/aseigler/fido2-net-lib/commit/994dac6d136920d980ae03681888e13f60338f10

**Comment by abergs** [comment]
On my phone but took a quick peek; looks a lot better 👌

**Comment by aseigler** [comment]
I do need to set some sort of sane timeout on the sync stuff to avoid a hang, but I think the async stuff is acceptable, but not particularly pretty.
