### ISSUE TITLE
Add Build Script

### ISSUE THREAD

**Issue by MeikTranel** [abergs/fido2-net-lib#62]
For contributors it is common practice to look at the readme.md and look for a how to build section. This is where a build script should exist that does the whole stack: setup, test and package - one console command should set off the whole thing.

This can be the same script that'll end up being called by future CICD integration.

**Comment by lennybacon** [comment]
I think msbuild would be fine. The idea is to have a start script/command to get it up and  running.

**Comment by MeikTranel** [comment]
The largest project i'm managing currently is entirely based on MSBuild logic. It includes several hundred C#, .NET and Delphi projects and with these kinds of projects MSBuild really is a strong suite. For small projects with single entry points, when dotnet pack on a solution file is all thats needed to produce release artifacts, i prefer things like Cake to control different steps. I'd much prefer PSake, as that would reduce some issues with VSCode-Omnisharp and Cake... but i haven't had enough experience with it yet.

**Comment by abergs** [comment]
Added simple scripts in 14f5b956bb0c646ba9008abfa478f3e6972a000e
Closing - but feedback is welcome 👍

**Comment by MeikTranel** [comment]
looks good to me, now put this somewhere in a CI environment. Appveyor, Azure DevOps, Travis... the sky is the limit here. They all give open source projects free build pipelines.

**Comment by abergs** [comment]
Should also add a note in Readme as well as a test script.

**Comment by MeikTranel** [comment]
Yes, i'm opening an issue to track CI setup for you.
