### ISSUE TITLE
Continuously integrate source code changes

### ISSUE THREAD

**Issue by MeikTranel** [abergs/fido2-net-lib#64]
Now that we have centralized build behavior in the repository in #62 we are set up to put all this stuff under CI, which will give us more confidence releasing and for consumers it helps tracking changes, builds and artifacts.

For open source projects, there's loads and loads of build automation providers offering free plans; Not all of them are set up to support .NET or the windows-only .NET Framework for that matter.
Ignoring windows most of them work fine tho.  With Windows the number of providers drops down to Azure DevOps and Appveyor (at least in my experience) - both of them are cool and absolutely fit for our needs.

**Comment by abergs** [comment]
@herrjemand would it be possible to run conformance tests in a CI/CD chain? Would be very nice.

**Comment by MeikTranel** [comment]
Depends on what exactly you mean by "conformance tests" - this could mean everything.

**Comment by abergs** [comment]
The version I have access to is an electron app. So the testing core is probably runnable with Node, but I would need to get my hands on a more script friendly packaging.

**Comment by herrjemand** [comment]
@MeikTranel The tools are freely available. You can request them here: https://fidoalliance.org/test-tool-access-request/

**Comment by abergs** [comment]
Closing this. A really nice addition would however to be able to run the conformance-tests through the CLI (@herrjemand has this on his roadmap and would be cool if you ping us when it's available to experiment with)

**Comment by herrjemand** [comment]
@abergs Ay ay
