### ISSUE TITLE
[Security] Remove dependency on PeterO.Cbor package 

### ISSUE THREAD

**Issue by abergs** [abergs/fido2-net-lib#7]
Decrease dependency count by removing the dependency on PeterO.Cbor and instead copy the CBOR decode implementation.

Disadvantage: No automatic updates in case of bugs in implmentation
Advantage: No package poisoning.

**Comment by redhook62** [comment]
Yes, it would certainly be more reliable when integrating into a software.

**Comment by abergs** [comment]
@aseigler Do you think his code would be hard to copy?

Repo: https://github.com/peteroupc/CBOR
License is Public Domain, so he is probably OK with this.

**Comment by redhook62** [comment]
I agree with you, it is actually not difficult to integrate. but I think I'll need a snapshot to deliver reliable server modules for production.
Thanks again to you for all the efforts you make

**Comment by aseigler** [comment]
I have a fix for this here https://github.com/aseigler/fido2-net-lib/commit/941bb2aeb7eea960fffccfaf5f889626ee917ed4 and here https://github.com/aseigler/fido2-net-lib/commit/28e41cb28b0c4c14454dfb527a39480df0e74389 but the PeterO.CBOR project file is configured to sign binaries with a PeterO.snk file which is missing.

I am guessing this is a very commit problem. What's the best resolution for it these days?

**Comment by peteroupc** [comment]
> I am guessing this is a very common problem. What's the best resolution for it these days?

That is a good question, and I have no answer for it, either.

**Comment by aseigler** [comment]
Best info I have found on the topic so far: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md.

**Comment by peteroupc** [comment]
Thank you for that, but that document doesn't discuss the other way around: What issues can happen when a new version of a library is no longer strong-named when previous versions were?  Fortunately, I am now working on version 4.0 of my CBOR library (in the 4.0 branch) and will consider removing the strong name from that version.

**Comment by abergs** [comment]
Thank you for joining in @peteroupc and for your work on the CBOR parser. We can definitely wait for the 4.0 package since this issue is a "long term" enhancement. The risk factor we want to remove is for example if someone were to gain control of your nuget package sometime down the line.

**Comment by aseigler** [comment]
The binding policy section kind of talks about a backward compatibility story, but not in a straightforward way like you describe. 

In the no drop-in replacement section it plainly recommends checking in the private key, the immediate thought of which makes me very uncomfortable as a foil hat wearing security practitioner. I wish they worded that sentence differently.

**Comment by peteroupc** [comment]
For your information, the signing key for my project is now checked in.

**Comment by aseigler** [comment]
Thanks for letting us know!
