### ISSUE TITLE
https://fido2.azurewebsites.net/ not working for Login on Chrome

### ISSUE THREAD

**Issue by briansboyd** [abergs/fido2-net-lib#71]
I'm able to perform Registration, but Login/Authentication simply hangs (Chrome specific).
Using both Yubikey 4 and 5 series authenticators.
I have tested this using three different Authenticators and two separate machines, all with the same result.
Any ideas?  Attached is a pic of what the hang looks like, as well as the selected options for registering/authenticating.
![fido2](https://user-images.githubusercontent.com/576897/50868706-12cec700-13f4-11e9-8029-e2d6356434e0.png)

Notes:
I see the same result when developing using the latest code using Chrome.
I was able to Login/Authenticate using my mobile phone (Google).
I was able to Login/Authenticate using Firefox, and this also works while developing with Firefox.

**Comment by abergs** [comment]
Confirmed that this is only a problem on Chrome.
Chrome doesn't seem to react to the fido2 key-tap. I can't see any related errors when tapping the key.

**Comment by aseigler** [comment]
I can repro issue in Chrome 71, but not Chome 73 (current dev).

**Comment by aseigler** [comment]
No repro on Chrome 72 either, which becomes stable in 20 days (https://www.chromestatus.com/features/schedule).

**Comment by briansboyd** [comment]
I've verified that the following website works with 2FA via FIDO2 in Chrome, written by some folks at Google:

https://webauthndemo.appspot.com/Home

I'll dig into this and check the difference between the inputs to navigator.credentials.get() and report back here.

**Comment by JuanDarioRV** [comment]
Hi @briansboyd , I'm sorry If I disturb to you, but I'm new on this technology and I am watching the code of this page https://fido2.azurewebsites.net/, but I don't have display the pop up of Yubico for to can read the fingerprint. Can you help me with that please?

**Comment by briansboyd** [comment]
Hi Juan,
Have you visited the Yubico developer site and watched the videos (https://www.yubico.com/why-yubico/for-developers/developer-videos/)?  I found it helpful to view all three.
It's not obvious why you are having that problem.  Try using the latest versions of either Chrome or Firefox.
Good luck learning these technologies!
Best,
Brian

**Comment by briansboyd** [comment]
I've verified that removing the empty 'transports' array allowed this flow to be unstuck.
This 'transports' array isn't currently being used anywhere in the code, so there's no loss of functionality.
It seems that coming versions of Chrome will use this, but this is at least a workaround until the next version of Chrome come out.

**Comment by abergs** [comment]
I'm hesitent to commit this (because it's against the spec) but if someone wants to write an if (chrome v71) transports = undefined on the client side if accept it.

**Comment by aseigler** [comment]
What if we initialize the array to full set of values for the enumeration (ble, internal, nfc, usb)? The intent is to allow any, after all. That might unstuck Chrome 71, I will try it when I get a chance if no one else gets to it first.

**Comment by aseigler** [comment]
@briansboyd, please verify this fix and report when you get a chance.

**Comment by briansboyd** [comment]
@aseigler This did the trick ... clean solution.

**Comment by aseigler** [comment]
Excellent @briansboyd, glad that worked! Will keep this issue resolved.
