### ISSUE TITLE
Receive DOMException when running Fido2Demo project

### ISSUE THREAD

**Issue by mrunks** [abergs/fido2-net-lib#76]
After downloading and attempting to run the project I receive the following error message when trying to use direct registration:

DOMException . webauthn.js line 214 .

This is occurring on navigator.credentials.create

I tried adding "cors" and credentials "include" to the /makeCredentials fetch but that did not affect the result.

**Comment by mrunks** [comment]
This is Chrome. I think I know what causes this and maybe you can confirm.

I am using Parallels VM with Windows 10 on my iMac.  So I am running code on windows even though I am on the mac and the Yubikey is plugged into the iMac.

I notice when I try the same test on your azurewebsites.net . I receive the same error message if I use the browser on the Virtual Machine but when I use the Chrome Browser on the iMac to access your site then it works.

Is there a work around for this ? Or is that part of the Attestation Type being Direct so I would need the device directly attached to the hardware of the OS ?

**Comment by aseigler** [comment]
I think you are pretty much correct.  Sounds like the browser in the VM is attempting to communicate with the authenticator but is failing, which is not too surprising given the circumstances.  When I try this scenario in a VM I get the same message from the browser as if I don't have an authenticator available.  I am unaware of any workarounds, but definitely seems like an authenticator->hypervisor->client breakdown.

**Comment by mrunks** [comment]
I noticed this happens when I try it with facebook too. Works on the regular OS but not on the VM.  Im closing this issue.
