### ISSUE TITLE
Windows Hello with Chrome and Win10 Build 1809

### ISSUE THREAD

**Issue by apurvabhansali** [abergs/fido2-net-lib#92]
Hi, I am running Windows 10 Build 1809 with support for FIDO2 w/Windows Hello.  Also running Chrome 74 w/WebAuthN support.  If I go to the demo site at ttps://fido2.azurewebsites.net/overview, I can register (using passwordless method) just fine with my Windows Hello PIN.  I have not enabled fingerprint, face or other method in Windows Hello, only PIN.  On registration, I am prompted to enter the PIN and I am then registered.

However, on sign-in (Assertion), I am prompted to enter a security key and do not get the prompt for PIN.  I am assuming there is something wrong in the AuthenticationExtensionsClientInputs that are passed into the getAsssertion, but I can not tell.

**Comment by aseigler** [comment]
Yeah, something is definitely very wrong with the demo site.  Not sure what happened, was working last I checked.  @abergs?

**Comment by apurvabhansali** [comment]
I actually saw the issue first in the . Asp net website I'm developing that is using the library.  Then I went back to the demo website to confirm the same behavior.  I made the authenticationclientinputs the same in assertion as it is in attestation but still see the problem.  Don't know if this is a windows hello issue.

**Comment by abergs** [comment]
Will look into this!

**Comment by abergs** [comment]
When I'm testing the security pin works well on Edge on Windows 1809. (I don't have any biometric input to test on my current computer).

Not sure that Chrome 74 allows ResidentKeys? I think i read that Chrome Canary just got support for it.
![image](https://user-images.githubusercontent.com/357283/58980463-b28c5780-87d0-11e9-8feb-6ec546595ec7.png)

**Comment by apurvabhansali** [comment]
ok, I also confirm that on Edge and Firefox 67, the pin box is coming properly.  You mentioned residentkeys - I have a question on this.  During attestation, we have set requireResidentKeys specifically to false, and the pin is allowed.  But during assertion, there is no mechanism to set parameters for authenticator selection .  Are you saying that you believe Chrome 67 just does not support any authenticators that do not have resident keys?  In that case I would think they should fail during attestation when requireResidentKeys is false because it is effectively required all the time.

**Comment by aseigler** [comment]
Looks like it's the appid extension that Chrome is puking on. 

https://github.com/abergs/fido2-net-lib/blob/b27fec1fb84a0c907d50f636d3919f33119eae5a/Fido2Demo/Controller.cs#L242

If you remove just the "AppID = _origin," part from that line, that seems to fix the problem.  Not sure what the deal is, that code has been there for quite a while and this scenario was definitely working recently.

**Comment by apurvabhansali** [comment]
Ok, yes, that has fixed the issue.  Do you want me to close this issue, or leave it open until you guys figure out the reason and/or make the fix in the gitHub repository?

**Comment by aseigler** [comment]
I think in the short term I will just remove that particular extension until I can figure out what happened.  This was working fine just a few weeks ago, which leads me to believe something changed very recently in Chrome.

Thanks for the report!

**Comment by abergs** [comment]
I will republish the demo-site
