### ISSUE TITLE
Demo site gets confused between Windows Hello and Security Key

### ISSUE THREAD

**Issue by Amethi** [abergs/fido2-net-lib#94]
On Windows 10 1903 where Windows Hello is FIDO2 certified, using any of the examples on the demo site (i.e. passwordless) assumes you want to use Windows Hello as the authenticator, rather than a FIDO2 key.

So you authenticate with Windows Hello (using pin in my case) and it registers you. Yay! But then when you go to sign-in, it prompts you to insert your security key... Umm... 

I've tried registering with a FIDO2 key inserted and the same happens, it locks you in to using Windows Hello authenticator. If you insert the key when signing in, it fails authentication as it doesn't expect that authenticator.

So there's two issues here:

1 - Windows Hello as a Fido2 authenticator doesn't work
2 - You can't choose which authenticator to use if you have more than one.

**Comment by abergs** [comment]
> But then when you go to sign-in, it prompts you to insert your security key... Umm...

Do you mean this screen? 
![image](https://user-images.githubusercontent.com/357283/61639222-5ce60e80-ac9b-11e9-8303-45819d3ef83f.png)

It's just a hard coded image and text and does not affect or reflect what authenticator is used.

Selecting authenticator is a responsible delegated to the Browser. What browser do you use?

**Comment by abergs** [comment]
I have confirmed that Security Keys and Windows Hello works on https://www.passwordless.dev/custom#heroFoot.

Choosing platform forces windows Hello.
Choosing crossplatform forces security key
Choosing Not specified suggests Windows Hello first and then Security key.
